### PR TITLE
feat: add KubectLayer and release as @aws-cdk/lambda-layer-kubectl-v28

### LINKED ISSUE #437: Support EKS 1.28
https://aws.amazon.com/blogs/containers/amazon-eks-now-supports-kubernetes-version-1-28/

### PR DESCRIPTION
**Pull request by mperochon**
Fixes #437

### CODE REVIEW

**Comment by gkaskonas** [comment]
Is it normal for the build to take 2 days?

**Comment by mperochon** [comment]
> Is it normal for the build to take 2 days?

It needs an approval by the maintainer

**Comment by mperochon** [comment]
Just a little followup for @pahud @kaizencc

**Comment by gkaskonas** [comment]
@pahud @kaizencc Sorry guys, can you approve, please? It's blocking us from upgrading

**Comment by caretak3r** [comment]
Can we migrate this project to cdk where we have active maintainers? Plus the documentation is unclear about how to use this in a python project.

**Review by dougalrea — APPROVED** [review]

**Comment by pahud** [comment]
Thank you @mperochon !! The build is pending for approval to run and I just hit it. Hopefully everything works great here.

After this PR is merged, we can advance https://github.com/aws/aws-cdk/pull/27502 to get 1.28 supported.

**Comment by pahud** [comment]
Hi @mperochon

I guess you'll need to run `yarn install && npx projen` again to update the `yarn.lock` and commit again.

Feel free to reach out and chat with me on cdk.dev slack if you need any help.

**Comment by mperochon** [comment]
Hi @pahud,

You're welcome, I'm just push the commit with the yarn.lock change.

Let me know if you need anything else

**Comment by pahud** [comment]
Hi @dougalrea can you take a look again?

**Review by kaizencc — APPROVED** [review]

**Pull request merged**
