### PR TITLE
feat: upgrade helm and kubectl version as @aws-cdk/lambda-layer-kubectl-v28

### LINKED ISSUE #437: Support EKS 1.28
https://aws.amazon.com/blogs/containers/amazon-eks-now-supports-kubernetes-version-1-28/

### PR DESCRIPTION
**Pull request by mperochon**
Fixes #437

### CODE REVIEW

**Comment by mperochon** [comment]
I fixed the base docker  from` public.ecr.aws/lambda/provided:latest` to `public.ecr.aws/lambda/provided:alami.2023.11.09.14`.

It seems the latest image is broken. I got `/bin/sh: line 1: yum: command not found` during the build.

**Comment by mperochon** [comment]
Just a little follow up @pahud @robertd @udaypant @cgarvis

**Comment by mperochon** [comment]
> I fixed the base docker from` public.ecr.aws/lambda/provided:latest` to `public.ecr.aws/lambda/provided:alami.2023.11.09.14`.
> 
> It seems the latest image is broken. I got `/bin/sh: line 1: yum: command not found` during the build.

Error found, thanks @kaizencc. We move yum to DNF package manager.

**Review by kaizencc — APPROVED** [review]
Thanks @mperochon !

**Pull request merged**
